apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-ingress-prod
  namespace: aks-istio-ingress
spec:
  secretName: istio-ingress-domain-cert-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  commonName: 'domain name'
  dnsNames:
    - 'domain name'
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io